repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1000']
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: ['--allow-multiple-documents']
        exclude: 'infra/sam/template.yaml|infra/workers/template.yaml'

-   repo: https://github.com/ambv/black
    rev: 24.3.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        args: ['--max-line-length=120', '--exclude=alembic/env.py']

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests]
        args: [--ignore-missing-imports, --namespace-packages, --explicit-package-bases]
        exclude: '^alembic/'

-   repo: local
    hooks:
    -   id: update-requirements
        name: Update requirements.txt
        entry: sh -c 'uv export --format requirements-txt > requirements.txt && git add requirements.txt'
        language: system
        files: '^pyproject\.toml$|^uv\.lock$'
        pass_filenames: false
        default_stages: [commit]
    -   id: pytest
        name: pytest
        entry: sh -c 'ENVIRONMENT=test uv run pytest'
        language: system
        types: [python]
        default_stages: [commit]
        require_serial: true
