.PHONY: deploy-dev deploy-prod remove-dev remove-prod

deploy-dev:
	npx serverless deploy --stage dev

deploy-prod:
	npx serverless deploy --stage prod

remove-dev:
	npx serverless remove --stage dev

remove-prod:
	npx serverless remove --stage prod