.PHONY: deploy-dev deploy-prod remove-dev remove-prod

deploy-dev:
	serverless deploy --stage dev

deploy-prod:
	serverless deploy --stage prod

remove-dev:
	serverless remove --stage dev

remove-prod:
	serverless remove --stage prod