"""Add post and post_image tables

Revision ID: fd77c7bf08e2
Revises: 49b2feb2dc7c
Create Date: 2025-09-16 19:01:15.808151+09:00

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "fd77c7bf08e2"
down_revision: Union[str, Sequence[str], None] = "49b2feb2dc7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
