"""Make birthday, gender, phone fields nullable

Revision ID: 0637ac8571c0
Revises: 529d579b6be8
Create Date: 2025-09-13 15:36:42.267817+09:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0637ac8571c0"
down_revision: Union[str, Sequence[str], None] = "529d579b6be8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "birthday", existing_type=sa.DATE(), nullable=True)
    op.alter_column("user", "gender", existing_type=mysql.TINYINT(display_width=1), nullable=True)
    op.alter_column("user", "phone", existing_type=mysql.VARCHAR(length=255), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "phone", existing_type=mysql.VARCHAR(length=255), nullable=False)
    op.alter_column("user", "gender", existing_type=mysql.TINYINT(display_width=1), nullable=False)
    op.alter_column("user", "birthday", existing_type=sa.DATE(), nullable=False)
    # ### end Alembic commands ###
