"""Add mission_id to post table

Revision ID: 605908b333e3
Revises: fdc12941d466
Create Date: 2025-09-16 19:11:55.176809+09:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "605908b333e3"
down_revision: Union[str, Sequence[str], None] = "fdc12941d466"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("mission_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "mission_id")
    # ### end Alembic commands ###
