"""Create post and post_image tables with proper schema

Revision ID: fdc12941d466
Revises: fd77c7bf08e2
Create Date: 2025-09-16 19:01:55.226866+09:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fdc12941d466"
down_revision: Union[str, Sequence[str], None] = "fd77c7bf08e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # user 테이블의 social_id에 인덱스가 없어서 먼저 인덱스 생성
    op.create_index("ix_user_social_id", "user", ["social_id"])

    op.create_table(
        "post",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("social_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["social_id"],
            ["user.social_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "post_image",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("file_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("upload_type", sa.Enum("PROFILE", "CONTENT", name="uploadtype"), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("post_image")
    op.drop_table("post")
    op.drop_index("ix_user_social_id", "user")
    # ### end Alembic commands ###
