"""Add unique constraint on social_id and mission_id in post table

Revision ID: 68998be89d14
Revises: 605908b333e3
Create Date: 2025-09-16 19:15:26.373552+09:00

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68998be89d14"
down_revision: Union[str, Sequence[str], None] = "605908b333e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_post_social_mission", "post", ["social_id", "mission_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_post_social_mission", "post", type_="unique")
    # ### end Alembic commands ###
