"""add index to post_like user_id and post_id

Revision ID: c577bb169764
Revises: 9f9f4749676c
Create Date: 2025-10-11 19:38:44.719130+09:00

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c577bb169764"
down_revision: Union[str, Sequence[str], None] = "9f9f4749676c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_post_like_post_id"), "post_like", ["post_id"], unique=False)
    op.create_index(op.f("ix_post_like_user_id"), "post_like", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_post_like_user_id"), table_name="post_like")
    op.drop_index(op.f("ix_post_like_post_id"), table_name="post_like")
    # ### end Alembic commands ###
