"""Change birthday type to int and remove phone field

Revision ID: 49b2feb2dc7c
Revises: 1a0ce3824700
Create Date: 2025-09-16 09:59:36.814732+09:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49b2feb2dc7c"
down_revision: Union[str, Sequence[str], None] = "1a0ce3824700"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "updated_at", existing_type=mysql.DATETIME(), server_default=None, existing_nullable=False)
    op.alter_column("user", "birthday", existing_type=sa.DATE(), type_=sa.Integer(), existing_nullable=True)
    op.drop_column("user", "phone")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("phone", mysql.VARCHAR(length=255), nullable=True))
    op.alter_column("user", "birthday", existing_type=sa.Integer(), type_=sa.DATE(), existing_nullable=True)
    op.alter_column(
        "user",
        "updated_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
