"""Add completed_at to user_mission

Revision ID: af466cc6a7af
Revises: 5068a70548aa
Create Date: 2025-09-30 13:12:58.634631+09:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af466cc6a7af"
down_revision: Union[str, Sequence[str], None] = "5068a70548aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post_image",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("file_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("upload_type", sa.Enum("PROFILE", "CONTENT", name="uploadtype"), nullable=False),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "challenge",
        "title",
        existing_type=mysql.VARCHAR(length=255),
        comment=None,
        existing_comment="챌린지 제목",
        existing_nullable=False,
    )
    op.alter_column(
        "mission",
        "title",
        existing_type=mysql.VARCHAR(length=255),
        comment=None,
        existing_comment="미션 제목",
        existing_nullable=False,
    )
    op.add_column("post", sa.Column("user_id", sa.Integer(), nullable=False))
    op.drop_index("uq_post_social_mission", table_name="post")
    op.create_unique_constraint(None, "post", ["user_id", "mission_id"])
    op.create_foreign_key(None, "post", "user", ["user_id"], ["id"])
    op.drop_column("post", "social_id")
    op.drop_index("ix_user_social_id", table_name="user")
    op.alter_column(
        "user_challenge",
        "status",
        existing_type=mysql.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        comment=None,
        existing_comment="챌린지 상태",
        existing_nullable=False,
    )
    op.alter_column(
        "user_challenge",
        "mission_step",
        existing_type=mysql.INTEGER(),
        comment=None,
        existing_comment="현재 진행 중인 미션 순서",
        existing_nullable=False,
    )
    op.add_column("user_mission", sa.Column("completed_at", sa.DateTime(), nullable=True))
    op.alter_column(
        "user_mission",
        "post_id",
        existing_type=mysql.INTEGER(),
        comment=None,
        existing_comment="미션 수행 포스트",
        existing_nullable=True,
    )
    op.alter_column(
        "user_mission",
        "status",
        existing_type=mysql.VARCHAR(length=50),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        comment=None,
        existing_comment="미션 상태",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_mission",
        "status",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=mysql.VARCHAR(length=50),
        comment="미션 상태",
        existing_nullable=False,
    )
    op.alter_column(
        "user_mission", "post_id", existing_type=mysql.INTEGER(), comment="미션 수행 포스트", existing_nullable=True
    )
    op.drop_column("user_mission", "completed_at")
    op.alter_column(
        "user_challenge",
        "mission_step",
        existing_type=mysql.INTEGER(),
        comment="현재 진행 중인 미션 순서",
        existing_nullable=False,
    )
    op.alter_column(
        "user_challenge",
        "status",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=mysql.VARCHAR(length=50),
        comment="챌린지 상태",
        existing_nullable=False,
    )
    op.create_index("ix_user_social_id", "user", ["social_id"], unique=False)
    op.add_column("post", sa.Column("social_id", mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, "post", type_="foreignkey")
    op.drop_constraint(None, "post", type_="unique")
    op.create_index("uq_post_social_mission", "post", ["social_id", "mission_id"], unique=True)
    op.drop_column("post", "user_id")
    op.alter_column(
        "mission", "title", existing_type=mysql.VARCHAR(length=255), comment="미션 제목", existing_nullable=False
    )
    op.alter_column(
        "challenge", "title", existing_type=mysql.VARCHAR(length=255), comment="챌린지 제목", existing_nullable=False
    )
    op.drop_table("post_image")
    # ### end Alembic commands ###
