"""챌린지-미션 M2M 관계로 변경 및 필드 수정

Revision ID: 5068a70548aa
Revises: 7dc8494bbd8a
Create Date: 2025-09-28 16:10:04.474640+09:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5068a70548aa"
down_revision: Union[str, Sequence[str], None] = "7dc8494bbd8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "challenge_mission",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("challenge_id", sa.Integer(), nullable=False),
        sa.Column("mission_id", sa.Integer(), nullable=False),
        sa.Column("step", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["challenge_id"],
            ["challenge.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["mission.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("challenge", sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column("challenge", sa.Column("goal", sa.Integer(), nullable=False))
    op.drop_column("challenge", "step")
    op.add_column("mission", sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column("mission", sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column("mission", sa.Column("point", sa.Integer(), nullable=False))
    op.drop_constraint(op.f("mission_ibfk_1"), "mission", type_="foreignkey")
    op.drop_column("mission", "challenge_id")
    op.drop_column("mission", "step")
    op.drop_column("mission", "reward_amount")
    op.add_column("user_mission", sa.Column("point", sa.Integer(), nullable=False))
    op.drop_column("user_mission", "reward_earned")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_mission", sa.Column("reward_earned", mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column("user_mission", "point")
    op.add_column("mission", sa.Column("reward_amount", mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column("mission", sa.Column("step", mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column("mission", sa.Column("challenge_id", mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f("mission_ibfk_1"), "mission", "challenge", ["challenge_id"], ["id"])
    op.drop_column("mission", "point")
    op.drop_column("mission", "type")
    op.drop_column("mission", "description")
    op.add_column("challenge", sa.Column("step", mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column("challenge", "goal")
    op.drop_column("challenge", "description")
    op.drop_table("challenge_mission")
    # ### end Alembic commands ###
