name: Production 배포

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: Python 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: SAM CLI 설정
        uses: aws-actions/setup-sam@v2

      - name: UV 설치
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Python 의존성 설치
        run: uv sync

      - name: AWS 자격증명 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: SAM 빌드
        working-directory: infra/sam
        run: sam build --config-env prod

      - name: 프로덕션 배포
        working-directory: infra/sam
        run: sam deploy --config-env prod --no-confirm-changeset --no-fail-on-empty-changeset

      - name: 배포 완료
        run: echo "프로덕션 배포가 완료되었습니다!"